### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by akshay-cemtrexlabs** [efremidze/Animoji#10]
lazy var AKPuppet = NSClassFromString("AVTPuppet") as! NSObject.Type

**Comment by efremidze** [comment]
what iOS version? device?

**Comment by akshay-cemtrexlabs** [comment]
IOS 13.3.1 iPhone X

**Comment by ElDuderini** [comment]
I am having the same error, only on a different line. I have been searching around for answers on how to solve it for hours, but I haven't gotten anywhere.

Here is the line it has problems with:
let bundle = Bundle(path: "/System/Library/PrivateFrameworks/AvatarKit.framework")!

**Comment by efremidze** [comment]
The bundle path might have been modified in iOS 13.3.1. If you can find the path, ill update it.
